name: NoMorePhantoms
version: ${project.version}
main: com.cdejong.nomorephantoms.NoMorePhantoms
api-version: 1.15
depend: [LuckPerms]
permissions:
  nomorephantoms.toggle:
    description: Players With this Permission can Toggle, Enable and Disable there own Phantom spawns.
    default: false
  nomorephantoms.toggle.others:
    description: Players With this Permission can Toggle, Enable and Disable other Players Phantom spawns.
    default: false
commands:
  phantom:
    description: Toggle, Enable and Disable Phantom spawns.
    usage: "Usage: /phantom [enable|disable]"
